-- Addresses --
INSERT INTO CUSTOMER_ADDRESSES (CUSTOMER_ADDRESS_ID, CITY, COUNTRY, STREET_NUMBER, PROVINCE, STREET_NAME, ZIP_CODE) VALUES (CUSTOMER_ADDRESS_SEQ.nextval, 'New Jersey', 'USA', 1934, 'NJ', 'Duke Lane', '07701');
INSERT INTO CUSTOMER_ADDRESSES (CUSTOMER_ADDRESS_ID, CITY, COUNTRY, STREET_NUMBER, PROVINCE, STREET_NAME, ZIP_CODE) VALUES (CUSTOMER_ADDRESS_SEQ.nextval, 'New Jersey', 'USA', 1816, 'NJ', 'Pinnickinnick Street', '07305');
INSERT INTO CUSTOMER_ADDRESSES (CUSTOMER_ADDRESS_ID, CITY, COUNTRY, STREET_NUMBER, PROVINCE, STREET_NAME, ZIP_CODE) VALUES (CUSTOMER_ADDRESS_SEQ.nextval, 'Baldwyn', 'USA', 4239, 'MS', '4239  Brownton Road', '38824');
INSERT INTO CUSTOMER_ADDRESSES (CUSTOMER_ADDRESS_ID, CITY, COUNTRY, STREET_NUMBER, PROVINCE, STREET_NAME, ZIP_CODE) VALUES (CUSTOMER_ADDRESS_SEQ.nextval, 'Scranton', 'USA', 3738, 'PA', 'High Meadow Lane', '18503');
INSERT INTO CUSTOMER_ADDRESSES (CUSTOMER_ADDRESS_ID, CITY, COUNTRY, STREET_NUMBER, PROVINCE, STREET_NAME, ZIP_CODE) VALUES (CUSTOMER_ADDRESS_SEQ.nextval, 'Mikkalo', 'USA', 2718, 'OR', '2718  Paul Wayne Haggerty Road', '97861');

-- Phone numbers --
INSERT INTO CUSTOMER_PHONE_NUMBERS (CUSTOMER_PHONE_NUMBER_ID, AREA_CODE, EXCHANGE, EXTENSION) VALUES (CUSTOMER_PHONE_NUMBER_SEQ.nextval, 1, 732, 7582496);
INSERT INTO CUSTOMER_PHONE_NUMBERS (CUSTOMER_PHONE_NUMBER_ID, AREA_CODE, EXCHANGE, EXTENSION) VALUES (CUSTOMER_PHONE_NUMBER_SEQ.nextval, 1, 504, 5017599);
INSERT INTO CUSTOMER_PHONE_NUMBERS (CUSTOMER_PHONE_NUMBER_ID, AREA_CODE, EXCHANGE, EXTENSION) VALUES (CUSTOMER_PHONE_NUMBER_SEQ.nextval, 1, 785, 6239225);
INSERT INTO CUSTOMER_PHONE_NUMBERS (CUSTOMER_PHONE_NUMBER_ID, AREA_CODE, EXCHANGE, EXTENSION) VALUES (CUSTOMER_PHONE_NUMBER_SEQ.nextval, 1, 858, 5414459);
INSERT INTO CUSTOMER_PHONE_NUMBERS (CUSTOMER_PHONE_NUMBER_ID, AREA_CODE, EXCHANGE, EXTENSION) VALUES (CUSTOMER_PHONE_NUMBER_SEQ.nextval, 1, 503, 5365902);

-- Contact details --
INSERT INTO CUSTOMER_CONTACT_DETAILS (CUSTOMER_CONTACT_DETAILS_ID, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME, CUSTOMER_ADDRESS_ID, CUSTOMER_PHONE_NUMBER_ID) VALUES (CUSTOMER_CONTACT_DETAILS_SEQ.nextval, 'kn66146ry8b@temporary-mail.net', 'John', 'HUDSON', 1, 1);
INSERT INTO CUSTOMER_CONTACT_DETAILS (CUSTOMER_CONTACT_DETAILS_ID, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME, CUSTOMER_ADDRESS_ID, CUSTOMER_PHONE_NUMBER_ID) VALUES (CUSTOMER_CONTACT_DETAILS_SEQ.nextval, 'ck22xn84vmw@temporary-mail.net', 'Tracey', 'SULLIVAN', 51, 51);
INSERT INTO CUSTOMER_CONTACT_DETAILS (CUSTOMER_CONTACT_DETAILS_ID, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME, CUSTOMER_ADDRESS_ID, CUSTOMER_PHONE_NUMBER_ID) VALUES (CUSTOMER_CONTACT_DETAILS_SEQ.nextval, 'uus6in7jnwm@temporary-mail.net', 'Andrew', 'BENITEZ', 101, 101);
INSERT INTO CUSTOMER_CONTACT_DETAILS (CUSTOMER_CONTACT_DETAILS_ID, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME, CUSTOMER_ADDRESS_ID, CUSTOMER_PHONE_NUMBER_ID) VALUES (CUSTOMER_CONTACT_DETAILS_SEQ.nextval, 'b7mh9k80xz@temporary-mail.net', 'Melissa', 'ROBINSON', 151, 151);
INSERT INTO CUSTOMER_CONTACT_DETAILS (CUSTOMER_CONTACT_DETAILS_ID, EMAIL_ADDRESS, FIRST_NAME, LAST_NAME, CUSTOMER_ADDRESS_ID, CUSTOMER_PHONE_NUMBER_ID) VALUES (CUSTOMER_CONTACT_DETAILS_SEQ.nextval, '3tad726x27c@temporary-mail.net', 'Tina', 'CANNING', 201, 201);

-- Customers --
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_REFERENCE, CUSTOMER_TYPE, CUSTOMER_CONTACT_DETAILS_ID) VALUES (CUSTOMERS_SEQ.nextval, 'Customer1', 0, 1);
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_REFERENCE, CUSTOMER_TYPE, CUSTOMER_CONTACT_DETAILS_ID) VALUES (CUSTOMERS_SEQ.nextval, 'Customer2', 1, 51);
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_REFERENCE, CUSTOMER_TYPE, CUSTOMER_CONTACT_DETAILS_ID) VALUES (CUSTOMERS_SEQ.nextval, 'Customer3', 2, 101);
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_REFERENCE, CUSTOMER_TYPE, CUSTOMER_CONTACT_DETAILS_ID) VALUES (CUSTOMERS_SEQ.nextval, 'Customer4', 3, 151);
INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_REFERENCE, CUSTOMER_TYPE, CUSTOMER_CONTACT_DETAILS_ID) VALUES (CUSTOMERS_SEQ.nextval, 'Customer5', 4, 201);


