version: '3.7'
networks:
  of-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/20
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    networks:
      of-network:
        ipv4_address: 192.168.96.3
    hostname: oracle
    container_name: oracle
    ports:
      - 49161:1521
      - 5500:5500
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
    volumes:
      - ../scripts/oracle:/docker-entrypoint-initdb.d
    #healthcheck:
      #test: echo "select * from v\$database;" | sqlplus -S sys/oracle as sysdba || exit 1
      #test: echo "select 1 from all_users where username = 'TOTO';" | sqlplus -S sys/oracle as sysdba || exit 1
      #timeout: 3s
      #retries: 30
  customers:
    image: customers:1.0-SNAPSHOT
    networks:
      of-network:
        ipv4_address: 192.168.96.2
    hostname: customers
    container_name: customers
    depends_on:
      - oracle
    ports:
      - 8080:8080
      - 9990:9990
    environment:
      JAVA_OPTS: "-Djboss.server.default.config=standalone-microprofile.xml -Djboss.http.port=8080 -Djboss.management.http.port=9990 -Dapp.context.root=test"
      ORACLE_PORT: 1521
      WILDFLY_PORT: 8080
    #entrypoint: /opt/jboss/wildfly/bin/run.sh
    command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
